### ISSUE TITLE
Functionalily of mTLS and it working

### ISSUE THREAD

**Issue by krrrahul** [nebhale/mtls-sample#2]
Hi 

 I am trying to find out the functionality of mTLS.
Its little hard for me to understand.Can you please answer my few of the question?

1.What properties do i need to do to change/add in cf manifest file to enable mTLS.?

2. Is mTLS is helpful if the apps are running of same cloudffundry i.e. they are using same wildcard domain?

3.If i am doing  certificate validation at gorouter level how we should modify the apps or mTLS it only helpful for third party apps to authenticate with apps running on cloudfoundry?

Can you please help me with these questions?

thanks in advance

**Comment by ghost** [comment]
Hi Ben,
To implement mutualTLS, we moved ssl termination from AWS ELB to goRouter.
We pushed client and server apps as mentioned in README.md.
After monitoring cf logs mtls-client we get following error:
```
Retrieving logs for app mtls-client in org oscf-sys / space production as admin...

   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT 2017-11-10 06:57:45.510 ERROR 11 --- [pool-1-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error o
ccurred in scheduled task.
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at io.pivotal.mtlssample.client.SerialNumberExtractor.getSerialNumber(SerialNumberExtractor.java:48) ~[classes/:
na]
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at io.pivotal.mtlssample.client.ClientApplication$Client.test(ClientApplication.java:67) ~[classes/:na]
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: null
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-
context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.ja
va:54) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_152]
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.j
ava:180) [na:1.8.0_152]
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294
) [na:1.8.0_152]
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_152]
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_152]
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
   2017-11-10T06:57:45.51+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_152]
   2017-11-10T07:02:45.51+0000 [APP/PROC/WEB/0] OUT 2017-11-10 07:02:45.510 ERROR 11 --- [pool-1-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error o
ccurred in scheduled task.
```
 are we missing any parameter??

Only difference we have in CF setup is our XFCC is set to `always forward`

Thanks,
Mandar

**Comment by nebhale** [comment]
The error message (which has been [improved](https://github.com/nebhale/mtls-sample/commit/c9c2b3f5344b07b17ba548fcdcb82b76004b2fcf)) seems to indicate that you don't have a client-side certificate configured.  I'd guess that you haven't configured Diego to set container identity.
